package com.kavit.docpat.hibernate.pojo;
// Generated Nov 5, 2020 4:56:18 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "db_hms")
public class Doctor implements java.io.Serializable {

	private Integer id;
	private String name;
	private String spl;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Doctor() {
	}

	public Doctor(String name, String spl, Set<Patient> patients) {
		this.name = name;
		this.spl = spl;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "spl", length = 45)
	public String getSpl() {
		return this.spl;
	}

	public void setSpl(String spl) {
		this.spl = spl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
